networks:
  default:
    external:
      name: roboshop
services:
  # docker run -d --name mongodb --network=roboshop mongodb:1
  mongodb:
    image: mongo:v1
    container_name: mongodb
  catalogue:
    image: catalogue:v1
    container_name: catalogue
    depends_on:
      - mongodb
  web:
    image: web:v1
    container_name: web
    depends_on:
      - mongodb
      - catalogue
    ports:
      -80:80
  